name: Deploy Quartz site to GitHub Pages
on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [notes_updated] # 核心：只要收到 obhub 发来的 notes_updated 暗号，立刻触发

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Blog Source
        uses: actions/checkout@v4

      - name: Clear Default Content
        run: rm -rf content

      - name: Fetch Latest Obsidian Notes from Obhub
        env:
          MY_TOKEN: ${{ secrets.QUARTZ_TOKEN }} # 👈 显式在这里捕获密钥
        run: |
          git clone https://$MY_TOKEN@github.com/ima-rius/obhub.git content

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm ci

      - name: Build Quartz
        run: npx quartz build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4